//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileupdateschedule
    {
        public short scheduleid { get; set; }
        public int fileid { get; set; }
        public Nullable<short> frequencyofrevision { get; set; }
        public Nullable<System.DateTime> scheduledatetime { get; set; }
        public Nullable<short> unitcodeupdfreq { get; set; }
        public Nullable<System.DateTime> updatedatetime { get; set; }
        public Nullable<int> upatedbyuserid { get; set; }
    }
}
