//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileviewaccesstype
    {
        public int viewaccessid { get; set; }
        public int fileid { get; set; }
        public string viewtypename { get; set; }
        public Nullable<short> departmentcode { get; set; }
    }
}
