//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileowner
    {
        public int ownershipid { get; set; }
        public int ownerid { get; set; }
        public int fileid { get; set; }
        public Nullable<short> ownerstatuscode { get; set; }
        public Nullable<System.DateTime> statusdate { get; set; }
        public Nullable<int> statusbyuserid { get; set; }
    }
}
