//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class filepublisher
    {
        public int publishid { get; set; }
        public int publisherid { get; set; }
        public int fileid { get; set; }
        public Nullable<short> publisherstatuscode { get; set; }
    }
}
