//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sopreport
    {
        public int FileID { get; set; }
        public string DeptFileName { get; set; }
        public string DeptSubFolderName { get; set; }
        public string DeptSubFolderName2 { get; set; }
        public string SPFileLink { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string VersionNo { get; set; }
        public string Approvedby { get; set; }
        public string DeptFileOwner { get; set; }
        public string SPFilePath { get; set; }
        public string SPFilePath_URL { get; set; }
        public string SOPFolder { get; set; }
        public string Department { get; set; }
        public Nullable<short> prioritycode { get; set; }
        public Nullable<short> filestatuscode { get; set; }
        public Nullable<System.DateTime> scheduledatetime { get; set; }
        public Nullable<int> NumberOfDays { get; set; }
        public string SOPFileStatus { get; set; }
        public string SOPNo { get; set; }
        public string SharepointApprovalStatus { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public Nullable<short> ApproverDeptCode { get; set; }
        public string ApproverName { get; set; }
        public Nullable<short> ApproverApprovalStatusCode { get; set; }
        public string ApproverApprovalStatus { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<short> OwnerDeptCode { get; set; }
        public string OwnerName { get; set; }
        public Nullable<short> OwnerApprovalStatusCode { get; set; }
        public string OwnerApprovalStatus { get; set; }
        public Nullable<short> ReviewerApprovalStatusCode { get; set; }
        public string Reviewers { get; set; }
        public Nullable<int> publisherID { get; set; }
        public Nullable<short> PublisherDeptCode { get; set; }
        public string PublisherName { get; set; }
        public Nullable<short> PublisherApprovalStatusCode { get; set; }
        public string PublisherApprovalStatus { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> NextUpdateDate { get; set; }
        public Nullable<int> changerequestid { get; set; }
        public string PublishURL { get; set; }
        public string DeptSubDepartment { get; set; }
        public string SignURL { get; set; }
        public string ChangeRequestURL { get; set; }
        public string SPFilePath_Error { get; set; }
    }
}
