//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwApprvrsSignature
    {
        public int fileid { get; set; }
        public int changerequestid { get; set; }
        public Nullable<int> requesterid { get; set; }
        public string approvername { get; set; }
        public string approvertitle { get; set; }
        public string AprvrSignedStatus { get; set; }
        public short AprvrSignedStatCode { get; set; }
        public Nullable<System.DateTime> Aprvrsigneddate { get; set; }
        public int approverid { get; set; }
        public string approveremail { get; set; }
    }
}
