//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOwnerSignature
    {
        public int fileid { get; set; }
        public int changerequestid { get; set; }
        public Nullable<int> requesterid { get; set; }
        public string ownerrname { get; set; }
        public string ownertitle { get; set; }
        public string ownerSignedStatus { get; set; }
        public short ownerSignedStatCode { get; set; }
        public Nullable<System.DateTime> ownersigneddate { get; set; }
        public int ownerid { get; set; }
        public string owneremail { get; set; }
    }
}
